OBJS-$(CONFIG_NLMEANS_FILTER)                += aarch64/af_afir_init.o
OBJS-$(CONFIG_NLMEANS_FILTER)                += aarch64/vf_nlmeans_init.o

NEON-OBJS-$(CONFIG_NLMEANS_FILTER)           += aarch64/af_afir_neon.o
NEON-OBJS-$(CONFIG_NLMEANS_FILTER)           += aarch64/vf_nlmeans_neon.o
